import '@/components/Accordions/Accordions.makeswift'
import '@/components/Marquee/Marquee.makeswift'
import '@/components/Tabs/Tabs.makeswift'
import '@/components/ProductGrid/ProductGrid.makeswift'
import '@/components/DimensionsBlock/DimensionsBlock.makeswift'
import '@/components/ValueBlockSection/ValueBlockSection.makeswift'
